version: "3.7"

x-db-envs: &db-envs
  POSTGRES_DB: devsprimedb
  POSTGRES_PASSWORD: password
  POSTGRES_USER: postgres

x-api-vars: &api-vars
  ALLOWED_HOSTS: 127.0.0.1,localhost
  DATABASE_URL: postgres://postgres:password@db:5432/devsprimedb
  DEBUG: 1
  SECRET_KEY: SOME_RANDOM_SET_OF_CHARACTERS_USED_AS_SECRET_KEY_#

services:
  db:
    image: postgres:13-alpine
    environment:
      <<: *db-envs
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5434:5439
  api:
    build:
      context: .
      target: base
    command: bin/start dev
    ports:
      - 18000:8000
    environment:
      <<: *api-vars
    depends_on:
      - db
    volumes:
      - ./tmp:/Bouncer_API_TeamA_Python08/tmp
      - ./project:/Bouncer_API_TeamA_Python08/project
      - ./bin/container:/Bouncer_API_TeamA_Python08/bin
      - ./requirements.txt:/Bouncer_API_TeamA_Python08/requirements.txt
