name: Clean City API

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Startup Services
        run: python -m pip install --upgrade pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Await Services
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Run Migrations
        run: python manage.py migrate
      - name: Run Tests
        run: python manage.py test
