# Generated by Django 3.2.9 on 2022-01-05 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created-at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated-at')),
                ('start_date', models.DateTimeField(null=True, verbose_name='task-start-date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='task-end-Date')),
                ('task_status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted')], default='Pending', max_length=30, verbose_name='task-status')),
                ('assigned_to', models.ManyToManyField(blank=True, limit_choices_to={'is_bin_collector': True, 'is_cleaner': True}, related_name='assignee', to=settings.AUTH_USER_MODEL, verbose_name='assigned-to')),
                ('checklist', models.ManyToManyField(related_name='checklist', to='clean_city.CheckList')),
                ('created_by', models.ForeignKey(limit_choices_to={'is_admin': True, 'is_manager': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='created-by')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='cleaning_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean_city.cleaningarea'),
        ),
    ]
