# Generated by Django 3.2.9 on 2021-12-31 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean_city', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
    ]
