# Generated by Django 3.2.9 on 2022-01-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_city', '0002_auto_20220105_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='cleaningarea',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
