# Generated by Django 3.2.3 on 2022-01-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean_city', '0002_alter_user_options'),
        ('clean_city', '0003_auto_20220110_0925'),
    ]

    operations = [
    ]
