# Generated by Django 3.2.9 on 2022-01-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_city', '0005_completedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='checklist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clean_city.checklist'),
        ),
    ]
