# Generated by Django 3.2.9 on 2022-01-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean_city', '0006_completedtask_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clean_city.task'),
        ),
    ]
