# Generated by Django 3.2.9 on 2022-01-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_city', '0007_completedtask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='cleaning_area',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='checklist',
        ),
        migrations.AddField(
            model_name='checklist',
            name='list',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cleaningarea',
            name='checklist',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='cleaning_area',
            field=models.ManyToManyField(blank=True, related_name='cleaning_area', to='clean_city.CleaningArea', verbose_name='cleaning-area'),
        ),
        migrations.AlterField(
            model_name='cleaningarea',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='CompletedTask',
        ),
    ]
