# Generated by Django 3.2.9 on 2022-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean_city', '0008_auto_20220129_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='Male', max_length=50),
            preserve_default=False,
        ),
    ]
